name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "dckr_pat_cKTGTdUpYf2lKOmVfuP9eXjO_sU" | docker login -u "uchimah" --password-stdin

      - name: Build Docker Image
        run: docker build -t uchimah/is147:${{ github.run_number }} .

      - name: Push Docker Image
        run: docker push uchimah/is147:${{ github.run_number }}
